# Generated by Django 4.2.9 on 2024-03-11 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_topic_options_questions_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='participants',
        ),
        migrations.AddField(
            model_name='topic',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
